# fly.toml app configuration file generated for shortly on 2023-04-29T13:41:09+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shortly"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
